apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: whhzghbj9-nodejs
  janus-idp.io/tekton: whhzghbj9-nodejs
  backstage.io/kubernetes-id: whhzghbj9-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: whhzghbj9-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
